<?php return array (
  'flosch\\slideshow\\Plugin' => 'plugins\\flosch\\slideshow\\Plugin.php',
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'rainlab\\pages\\Plugin' => 'plugins\\rainlab\\pages\\Plugin.php',
  'RainLab\\Pages\\Classes\\Controller' => 'plugins\\rainlab\\pages\\classes\\Controller.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins\\rainlab\\pages\\classes\\Router.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins\\rainlab\\pages\\classes\\PageList.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins\\rainlab\\pages\\classes\\Page.php',
  'RainLab\\Pages\\Components\\StaticPage' => 'plugins\\rainlab\\pages\\components\\StaticPage.php',
  'RainLab\\Pages\\Classes\\Snippet' => 'plugins\\rainlab\\pages\\classes\\Snippet.php',
  'RainLab\\Pages\\Classes\\SnippetManager' => 'plugins\\rainlab\\pages\\classes\\SnippetManager.php',
  'Flosch\\Slideshow\\Components\\Slideshow' => 'plugins\\flosch\\slideshow\\components\\Slideshow.php',
  'Flosch\\Slideshow\\Models\\Slideshow' => 'plugins\\flosch\\slideshow\\models\\Slideshow.php',
  'Flosch\\Slideshow\\Models\\Slide' => 'plugins\\flosch\\slideshow\\models\\Slide.php',
  'RainLab\\Pages\\Components\\StaticMenu' => 'plugins\\rainlab\\pages\\components\\StaticMenu.php',
  'RainLab\\Pages\\Classes\\Menu' => 'plugins\\rainlab\\pages\\classes\\Menu.php',
  'RainLab\\Pages\\Classes\\MenuItem' => 'plugins\\rainlab\\pages\\classes\\MenuItem.php',
  'RainLab\\Pages\\Classes\\MenuItemReference' => 'plugins\\rainlab\\pages\\classes\\MenuItemReference.php',
);